### PR TITLE
Fix missing dots in Cyrillic i and j

### PR DESCRIPTION
**Pull request by Mystic-Mirage**
For some reason, Noto fonts replace Cyrillic letters i and j by dotless form -- ı and ȷ.
This is wrong and should be fixed. Here is the issue describes the problem -- googlei18n/noto-fonts#1051

I've found this behavior declared here:
```
script cyrl;
sub afii10103 by afii10103dotless;
sub afii10105 by afii10105dotless;
```
So my patch just comments out these two 'sub *' lines.

### CODE REVIEW

**Comment by Mystic-Mirage** [comment]
The second commit is about combining diacritics. Need to keep dot while using acute accent (for example).

**Comment by moyogo** [comment]
@Mystic-Mirage The dot should be removed when used with top diacritics like the acute accent.
The characters і and ј (U+0456 and U+0458) have the soft-dotted property: https://unicode.org/cldr/utility/list-unicodeset.jsp?a=[:Soft_Dotted=Yes:]

**Comment by Mystic-Mirage** [comment]
@moyogo Yes, you're right. Thank you!

I've removed the wrong commit from this PR

**Comment by Kharacternyk** [comment]
Ukrainian here. Any news on it? KDE Plasma uses Noto as a default font (AFAIK, Chrome OS too) and it means that the out-of-the-box look for some users from East Europe is just broken.

**Comment by Mystic-Mirage** [comment]
@Kharacternyk Чекаємо...

**Comment by Mystic-Mirage** [comment]
Happy 1 Year Anniversary! 🍰

**Comment by Kharacternyk** [comment]
Жах. Схоже, що _nobody cares_.

**Pull request merged**
