### PR TITLE
Updated Noto Adlam and Tifinagh Fonts 

### PR DESCRIPTION
**Pull request by NeilSureshPatel**
Updated Noto Adlam and Tifinagh Fonts from JamraPatel. Tifinagh has been updated to version 2.002 to fix issues with custom parameters caught with noto_lint.py.

### CODE REVIEW

**Comment by NeilSureshPatel** [comment]
@anthrotype, thanks for clarifying the issues. There was lack of clarity on providing the deliverables. We were asked for test fonts and .fea files, but it was never clear if those were to be included in the repository. The .fea files are indeed redundant as they are part of the Glyphs sources. I can remove the .ttfs and the .fea files. 

The situation with the README and CHANGELOG was the same. @davelab6 asked for details from email correspondence to be added to Github. Is the norm to just use a README file? I can move the CHANGELOG details into the README if that is the case. 

In regards to the Instances subdirectories in Noto Sans Tifinagh, this is part of a bigger change to Tifinagh. The new design of Tifinagh supports 12 different writing traditions each with it own glyphs source. This was the solution we settled on with @marekjez86 and @davelab6 to overcome a limitation in available lang tags that prevents all glyph variations to work properly from a single font.  Noto Sans Tifinagh Master Glyphs file employs some custom parameters that fontmake does not process properly, so in a way it ends up being a working file. Final fonts need to be generated from the sources for each writing tradition(instance). What would be the best way to organize the sources?

**Comment by anthrotype** [comment]
thanks for the clarifications

> This was the solution we settled on with @marekjez86 and @davelab6 

ok, I'll defer to them.

> Noto Sans Tifinagh Master Glyphs file employs some custom parameters that fontmake does not process properly, so in a way it ends up being a working file

I'd be curious to know what these are.

**Comment by NeilSureshPatel** [comment]
> I'd be curious to know what these are.

The problematic custom parameters are, Replace Feature and Remove Prefixes.

**Comment by anthrotype** [comment]
these are supposed to work, at least for instances. If they don't it's a bug. Would be great if you could send a detailed bug report at googlefonts/glyphsLib repo. Thanks

**Comment by anthrotype** [comment]
Correction. Replace Feature is supported, but "Remove Prefix" isn't. I wasn't even aware the latter existed. We do support a "Replace Prefix" custom parameter though. Would that work for you? E.g. replace some prefix with an empty string (same as removing).

**Comment by NeilSureshPatel** [comment]
> We do support a "Replace Prefix" custom parameter though. Would that work for you? E.g. replace some prefix with an empty string (same as removing).
Would that mean I would create additional lookups that are empty and then replace the lookups that I want to remove with those? if so I think that might work. I would have to try it out.

**Comment by anthrotype** [comment]
something like that.
Alternatively could you open an issue about the unsupported custom parameter detailing how it is supposed to work. It's hard to keep up with all the new custom parameters that periodically pop up...
Thanks!

**Comment by NeilSureshPatel** [comment]
Ok, let me touch base with Zachary Scheuren. He is the one that brought it to my attention and he might already be submitting an issue. In the mean time I'll try the Replace Feature parameter to see if it works. It would be nice to not have 12 source files. Thanks!

**Comment by anthrotype** [comment]
Committing the removal of the binary TTF files is not enough to purge them from the git history. You need to rebase on the current master and edit or remove the commits where you added those files.

**Comment by NeilSureshPatel** [comment]
> Committing the removal of the binary TTF files is not enough to purge them from the git history. You need to rebase on the current master and edit or remove the commits where you added those files.
I apologize I think I have made a mess here. I was trying to resolve the conflict with the Adlam source files since I believe Marek had deleted the old ones. In any case when I tried to merge upstream changes into my fork it reports that all of my Tifinagh files are in a folder called NotoSerifGrantha, which makes no sense to me. Would it make sense to create a new fork and upload the files correctly there?

**Comment by anthrotype** [comment]
Yes, better to start from clean slate.

**Comment by marekjez86** [comment]
Thanks...

**Comment by NeilSureshPatel** [comment]
@marekjez86 @anthrotype  I have updated all of the Adlam and Tifinagh sources, checked them with noto_lint and fixed any errors. Before I upload and create a new pull request, I wanted to confirm something. Using the Replace Prefix parameter, I was able to get Noto Sans Tifinagh to work from a single file that produces all the instances correctly. Currently, the noto_source repository has 2 Tifinagh sources. One called NotoSansTifinagh-Regular.glyphs and and another called NotoSansTifinagh.glyphs. Currently, my file is named NotoSansTifinagh-Master.glyphs since its scope is larger than the original. However, I think to fit with the current naming convention I should call it NotoSansTifinagh.glyphs. Is that correct?

**Comment by anthrotype** [comment]
Sounds good to me

**Comment by NeilSureshPatel** [comment]
One more question. Since Adlam and Tifinagh are not in subdirectories do we just exclude the README files that were associated with them and put any relevant info in the commit notes? Thanks.

**Comment by anthrotype** [comment]
Yes, makes sense

**Pull request closed without merging**
