### PR TITLE
Set script on all mand glyphs to fix GPOS issues

### PR DESCRIPTION
**Pull request by punchcutter**
Fixes https://github.com/googlefonts/noto-fonts/issues/1504

### CODE REVIEW

**Comment by dscorbett** [comment]
What is it that needs `script` for anchors to work right? (I’m just starting to learn about fontmake and I’m wondering if this is a bug in fontmake instead of in this font.)

**Comment by punchcutter** [comment]
In Glyphs there is information associated with each glyph for script, category (Letter or Mark are the main two we care about), and subcategory (Nonspacing is what matters the most for marks to get GDEF class 3). That information isn't stored in the Glyphs file by default so it requires a Python script to run and store it. I wouldn't consider it a bug in fontmake because fontmake can't possibly know what script is associated with a glyph unless it has a Unicode value associated with a script or is named in a way that can be parsed. That works half the time, but what about the other half? Since fontmake builds a GDEF based on that information we need to give it somehow. Storing the correct properties in the Glyphs file is one way to provide that and what we've done for half of Noto to ensure these GDEF classes get set correctly. 
For this one I made it store the script tag for each 'mand' glyph in the Glyphs file so when fontmake is building GPOS it correctly associates 'mand' bases with 'mand' marks and then GPOS works as expected.

**Comment by marekjez86** [comment]
@punchcutter ： You updated the glyphs file. In the meantime I switched this one and many others (but not all) to UFOs+designspace... What I did instead is took your src/NotoSansMandaic.glyphs , converted to UFOs+designspace and updated the master with it.

Therefore this pull request is not required any longer because it's applied in the tree already. Please advise me if I can close it.

**Comment by punchcutter** [comment]
Sounds good!

**Pull request closed without merging**
