### PR TITLE
Reapply PR125

### PR DESCRIPTION
**Pull request by rdaysky**
The changes introduced by previously merged PR #125 were overwritten by upstream updates from #213. This PR contains exactly the same changes as #125. Please apply these changes again and make sure to pass them upstream.

The object of the changes is fixing the dot over the Cyrillic letters Іі and Јј, which is mistakenly hidden.

### CODE REVIEW

**Comment by rdaysky** [comment]
@googlebot I signed it!

**Comment by marekjez86** [comment]
Thank you and sorry about the process mess up.

**Comment by marekjez86** [comment]
@rdaysky : Roman, could you check one or two fonts in https://github.com/googlefonts/noto-fonts ?

**Comment by rdaysky** [comment]
@marekjez86 At a glance seems OK

**Pull request merged**
