### PR TITLE
Noto Sans Myanmar 2.104 [WIP]

### PR DESCRIPTION
**Pull request by simoncozens**
This addresses some of the issues in https://github.com/googlefonts/noto-fonts/issues/1926; @ohbendy will add some drawing fixes before this is releasable.

### CODE REVIEW

**Comment by marekjez86** [comment]
@ohbendy : is it release-able? I saw that you added some work. are you done?

**Comment by ohbendy** [comment]
@simoncozens should I check those fixes or are you confident they address all the issues reported in that thread on Mon?

**Comment by simoncozens** [comment]
I’m happy with them; I don’t want to make you test any more Myanmar shaping for quite a while…

**Comment by ohbendy** [comment]
In that case yes we can release this version. Just another reminder it's only a few little fixes for Mon language, the fonts are generally quite badly broken still :-)

**Pull request merged**
